# cffi_bridge.pyi — hand-written type stubs for the CFFI/ctypes binding.
#
# The actual implementation (cffi_bridge.py) loads engine_c.dll via ctypes.
# This file enables IDE autocompletion and mypy type checking for users who
# write scripts importing Engine, Scene, GameObject, Component.

from typing import Callable, Optional

class Component:
    """Wrapper around a C ComponentHandle."""
    @property
    def type_name(self) -> str: ...

class GameObject:
    """Wrapper around a C GameObjectHandle (owned by Scene)."""
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...
    def add_component(self, type_name: str) -> Optional[Component]: ...
    def get_component(self, type_name: str) -> Optional[Component]: ...

class Scene:
    """Wrapper around a C SceneHandle (owned by Engine)."""
    def create_object(self, name: str) -> Optional[GameObject]: ...
    @property
    def object_count(self) -> int: ...

class Engine:
    """Pythonic wrapper around C EngineHandle — ctypes-based.

    Usage:
        engine = Engine('{"app":"demo"}')
        engine.init()
        scene = engine.create_scene("Main")
        ...
        engine.shutdown()
    """
    def __init__(self, config_json: str = "{}") -> None: ...
    def init(self, config_json: str = "{}") -> bool: ...
    def shutdown(self) -> None: ...
    @property
    def is_initialized(self) -> bool: ...
    def update(self, dt: float) -> None: ...
    def create_scene(self, name: str) -> Optional[Scene]: ...
    def get_scene(self, name: str) -> Optional[Scene]: ...
    def subscribe(self, event_type: str, callback: Callable[[str], None]) -> int: ...
    def publish_event(self, event_type: str, data: str) -> None: ...
    def mass_spawn(self, scene_name: str, count: int, prefix: str = "obj") -> None: ...
